config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users, only: [:create] 

  get '/users/create' => 'users#new'
  post '/users' => 'users#create'

  post '/' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/sounds' => 'sounds#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def auhtorize
  	redirect_to '/' unless current_user
  end 
  
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

	def new
		if session[:user_id]
			redirect_to sounds_path
		end
	end

	#/
	def create
		user = User.find_by({email: params[:email]})
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] ="That's the right on, Man."
			redirect_to sounds_path(@sounds)
		else
			flash[:notice]="Either your e-mail or password didn't work. Please try again."
			render :new
		end
	end

	#/logout
	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged Out Nowabouts."
		redirect_to "/"
	end

end

app/controllers/sounds_controller.rb
class SoundsController <ApplicationController
	before_action

	def index
		@user = User.find(session[:user_id])
	end

end

app/controllers/users_controller.rb
class UsersController <ApplicationController

def new
	@user = User.new 
end

def create
	@user = User.create({
		first_name: params[:user][:first_name], 
		last_name: params[:user][:last_name], 
		email: params[:user][:email], 
		password: params[:user][:password], 
		password_confirmation: params[:user][:password_confirmation]
	}) 
	redirect_to root_path
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundShaperApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= yield :css %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sounds/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sound Shapers</title>
	<script src="howler.js"></script>
	<script src="pedalboard.js"></script>
	<script src="/dancer/dancer.js"></script>
</head>
<body>

	<div id="banner">
		<h1>Sound Shaper</h1>
	</div>
	
	<div id="sounds-container">
		<div id="global-controls">
			<button id="play-all" class="control-btn">Play All</button>
			<button id="pause-all" class="control-btn">Pause All</button>
			<button id="reset-all" class="control-btn">Reset All</button>
			<button id="fade-out" class="control-btn">Fade Out</button>
		</div>
		<div id="mute-buttons">
			<button id="mute-guitar" class="sound-btn">Mute Guitar</button>
			<button id="mute-piano" class="sound-btn">Mute Piano</button>
			<button id="mute-drums" class="sound-btn">Mute Drums</button>
			<button id="mute-bass" class="sound-btn">Mute Bass</button>
		</div>
		<div id="effects">
			<button id="overdrive-guitar" class="overdrive">Overdrive</button>	
		</div>
		<p><%= link_to "Log Out", logout_path, class: "btn grid-3-8" %><p>
	</div>

	
	<script src="sounds.js"></script>
	<script src="effects.js"></script>
</body>
</html>

app/views/users/new.html.erb
<div id="banner">
		<h1>Sound Shaper</h1>
</div>

<div id="welcome-wagon">
	<h4>Sign up For Sound Shaping</h4>
	<ul class="login grid-6-8">
		<%= form_for @user, :url => users_path do |f|%>
			<li><%=f.label :first_name%></li>
			<li><%=f.text_field :first_name%></li>
			<li><%=f.label :last_name%></li>
			<li><%=f.text_field :last_name%></li>
			<li><%=f.label :email%></li>
			<li><%=f.text_field :email%></li>
			<li><%=f.label :password%></li>
			<li><%=f.password_field :password%></li>
			<li><%=f.label :password_confirmation%></li>
			<li><%=f.password_field :password_confirmation%></li>
			<p><%=f.submit "Submit", :class => 'btn' %></p>
		<%end%>
	</ul>
	<a href="/"> Back to Sign In</a>
</div>